### PR TITLE
optionally give Fermi energy in Wannier90 converter

### PR DESCRIPTION
**Pull request by jkarp314**
I edited the wannier90 converter to allow the user to optionally give a DFT Fermi energy at the end of the .inp file. The Fermi energy is subtracted from the H(r = 0) term. 

I also included a test which checks that the resulting hopping is the same as the original hopping minus the given Fermi energy.

### CODE REVIEW

**Comment by the-hampel** [comment]
For me these changes look all good! However, we still would need to adapt the documentation. @jkarp314 could you please add this option in the documentation? The file that needs to be adjusted is this one: https://github.com/TRIQS/dft_tools/blob/2.2.x/doc/guide/conv_W90.rst , and the linked inp file in there. After that we can merge.

**Comment by jkarp314** [comment]
@the-hampel thanks for the response!

I made the changes that you requested. Does it look good now?

**Comment by mzingl** [comment]
I looked at this pull request. Looks good to me. My only suggestion is to add to the documentation:
1.) That the Fermi energy is in eV
2.) Explain that the code subtracts the Fermi energy from the Hamiltonian. This means that the Fermi energy is essentially zero in the model. If it is not provided then the Fermi energy is the one of the Hamiltonian. I would point out that this should be avoided. There are some functions in DFTTools which implicitly assume a Fermi energy of 0 eV.

**Comment by jkarp314** [comment]
@mzingl thanks! 

I updated the rst file according to your suggestions

**Review by the-hampel — APPROVED** [review]
I think this looks good now and is ready to be merged? Any objections?

**Pull request merged**
