### PR TITLE
[PLOVasp] Fix incorrect equivalence determination of correlated shells

### PR DESCRIPTION
**Pull request by opeil**
This PR fixes an issue causing incorrect assignment of (in-)equivalent correlated shells in the resulting *.h5 file

Closes issue #235

Changes:
- Add test for NiO with two correlated shells
- Add debug logging to PLOVasp routines

Bugfixes:
- Modify the meaning of `ion_sort` member of `proj_shell`. Now it contains the actual ion index corresponding to POSCAR.
- Fix `shion_to_shell` in `VaspConverter` to make `proj_mat` be filled correctly for multiple correlated shells

### CODE REVIEW

**Comment by opeil** [comment]
This PR is not complete at the moment because I have not yet checked the projectors themselves. The problem with projectors seems to be related to some relatively recent changes to `VaspConverter` and I need to carefully check whether the logic is correct for all kinds of workflows.

@merkelm: Could you please check that the added test case for NiO is what was causing the issue for you? You can also check whether `nio.ref.h5` contains an expected output (save for projectors themselves).

**Comment by opeil** [comment]
Added a fix for the issue with incorrect projectors. Hope it will not break current scripts. It would be nice to add more tests with various use cases.

**Comment by merkelm** [comment]
Dear @opeil, thank you for the fixes and sorry for the late reply! The test case indeed covers the previous error. The new output using this branch and the `nio.ref.h5` look good, where I checked the `corr_shells/sort`, `shells/sort` and where the projectors have nonzero elements.

Please let me know if there's anything else I can help you with!

**Review by the-hampel — APPROVED** [review]

**Comment by the-hampel** [comment]
Hi @opeil ,
thank you fixing this. I had a look at the code and tested it. All looks good to me as Max already also found! 

Only sphinx autodoc had a problem building the documentation (jenkins detected that). Somehow by numpydoc standards each class has to have a init function. So I added a default init for the `PloFormatter`. This seems to not influence the output of the logger. But maybe you can quickly check if that makes sense to you. 

If you agree and all tests pass I will merge this.

**Pull request merged**
