### PR TITLE
VASP interface update

### PR DESCRIPTION
**Pull request by opeil**
* One small feature (requested by some users) for the input file is added

* Docs for VASP conversion interface (only the one in the main Guide) are updated

Still working on other doc files... More PRs to come.

P.S. Unfortunately, I cannot really see how the docs will look in production. I only managed to compile sphinx docs separately from the main TRIQS docs. DFTTools docs seem to be almost completely independent and it is not clear why on earth there are all these requirement (clang + libclang +....) to compile DFTTools docs.

### CODE REVIEW

**Comment by opeil** [comment]
Jenkins is complaining: no idea why. I can definitely build the branch on my machine and all tests pass. However, I cannot check doc builds (some requirements I cannot fulfill). Could someone tell me what the problem is?

**Comment by mzingl** [comment]
Hi Oleg,
many thanks!

I guess your doc problems are related to issue #100 and to TRIQS issue TRIQS/triqs#605
This is also stopping me from some work on the doc.

@parcollet and @Wentzell can you have a look at this problem?

Best,
Manuel

**Comment by mzingl** [comment]
Hi Oleg,

first of all, the doc should compile now.
I put the vasp branch on top of the current unstable.
The vasp-update-2.0 is now on-top of the vasp branch, so it is:
unstable -- vasp -- vasp-update-2.0.
Should we merge all of this (vasp + vasp-update-2.0) into unstable?

Best,
Manuel

**Comment by mzingl** [comment]
And I should add: I did this with rebases, so you will need to force reset/rebase your local branches.

**Pull request merged**
