### PR TITLE
Analyze block structure from gf

### PR DESCRIPTION
**Pull request by gkraberger**
Hi everyone,

- I put the ``deg_shells`` from the SumkDFT class into the BlockStructure class (ensuring backward compatibility) because it logically belongs there, and updated the test.
- I added an ``analyse_block_structure_from_gf`` function to SumkDFT. The reason is that in the general case it is not safe to just investigate the density matrix and Hloc  to find the block structure. When checking the whole non-interacting Green's function as obtained from ``extract_G_loc``, we detect all off-diagonal elements that are there.
- I now have a more sophisticated routine to detect degenerate orbitals. For matrix-valued Green's functions, the block structure detection often gives back the orbitals in a different order in different blocks. Then, these blocks are never found to be equal. Furthermore, when SOC is involved, it is sometimes necessary to complex conjugate one block before it is equal to the other. Therefore, two blocks ``G_1`` and ``G_2`` are considered equivalent now if there exists a unitary transformation ``T`` so that ``maybe_conjugate(T G_1 T^dagger) = G_2``. The function ``analyse_deg_shells`` tries to find such a matrix ``T``. In ``SumkDFT.deg_shells``, for each block in a group of equivalent blocks, a transformation matrix and whether to conjugate is additionally saved. There is a test.
- The ``SumkDFT.symm_deg_gf`` function now works both with the old format of ``SumkDFT.deg_shells`` (for backwards-compatibility) and with the new format (as described above). This is also tested.

For now, the (old) ``SumkDFT.analyse_block_structure`` function and the ``use_dft_blocks`` flag are still supported (using the old algorithm). We should think whether we want to keep them in for simple cases (e.g., SrVO3) where they work. This has the advantage that one does not need to use extract_G_loc before one knows the block structure (as opposed to my new algorithm). But it has the disadvantage that, for some systems, it might give wrong block structures and find not all symmetries. What's your opinion on that, shall we keep it as-is, deprecate it, or remove it?

Best
Gernot

### CODE REVIEW

**Comment by mzingl** [comment]
Hi all,

this pull request allows to determine the block structure and degenerate orbitals from G_loc, because using the density matrix and/or H_loc can be ambiguous in special cases. Besides some minor points, which we have already discussed, there are a few points others might be also interested in.

- There are two main functionalities: `analyse_block_structure_from_gf` determines the block structure and analyse_deg_shells determines the degenerate orbitals for a given G. 
   - `analyse_block_structure_gf`: To use this, one has to perform an initial `extract_G_loc()`, which further requires to use `set_Sigma()` first (with a self-energy set to zero). I usually take the default self-energy from the ctyhb solver, but for initializing the solver one needs again information on the block structure. So the workflow to use `analyse_block_structure_from_gf` is not completely clear. Gernot, can you provide an example here? Gernot also told me that the block structure is usually determined correctly with the old algorithm, thus we should keep the old one as standard. The old one is also faster, because no `extract_G_loc()` is required.

   - `analyse_deg_shells`: This can be easily incorporated into the standard workflow as it can be called after the first `extract_G_loc()`. It is useful when not all symmetries are detected from the density matrix.

- How can we use all of this for real-frequency calculations?

- `conjugate_in_tau()`: Should this be provided by the TRIQS library?

- `threshold` has now a different (and multiple) meanings, this should be documented.

- We need a user guide page. The idea would be to show on an example how calculations for systems with SO and off-diagonal hybridization can be performed. I'm fine with  opening an issue for the user guide update when we pull this request.

Regards,
Manuel

**Comment by gkraberger** [comment]
- Let me clarify the ``set_Sigma`` issue a little bit. In order to use ``analyse_block_structure_from_gf``, one needs to first ``extract_G_loc``, and to use ``extract_G_loc`` one needs to provide a (possibly zero) Sigma. This is needed because ``extract_G_loc`` takes the mesh for Gloc from Sigma. But we need Sigma and Gloc to have the same mesh as ``S.Sigma_iw`` and ``S.G_iw`` in the Solver (I'm thinking primarily about CTHYB, of course). Right now, this is not a problem because the old ``analyse_block_structure`` does not need to first ``extract_G_loc``. 

    As we do not want to completely change the workflow, the idea is to leave the old ``analyse_block_structure`` as standard and it's the responsability of the user to check if the found block structure is correct. At least I usually look at ``dos_wannier_basis`` first, from which you see the block structure. If the old ``analyse_block_structure`` gives a different result, one can change to ``analyse_block_structure_from_gf``.

    For these rare cases, the workflow would be
    ```
    # the usual imports and definitions
    SK = SumkDFT(filename, use_dft_blocks=False)
    Sigma_zero = SK.block_structure.create_gf(beta=beta)
    SK.put_Sigma([Sigma_zero])
    G = SK.extract_G_loc() # this usually takes a while
    SK.analyse_block_structure_from_gf(G)
    # save SK.block_structure to h5 and load in the following calculations after setting up SK
    # in the following, the usual python script as before (but without constructing SK)
    ```
- Right now, ``conjugate_in_tau()`` only works for ``GfImFreq``. Therefore, in the most general case, the ``symm_deg_gf`` function will only work for ``GfImFreq``. We have to generalize this to other types of Gf. Would it be sufficient to extend it to ``GfReTime``, ``GfImTime`` and ``GfReFreq`` or should the ``symm_deg_gf`` function also work for more complicated Green's functions?

- The basic meaning of ``threshold`` is still that it is okay to treat values smaller than ``threshold`` as zero. So, before ``threshold`` meant that if an off-diagonal matrix entry of the density matrix and Hloc are both < ``threshold``, it is ok to modify the block structure so that this off-diagonal entry is set to zero. Similarly, if the difference between two blocks is smaller than ``threshold``, it is ok to assume that they are degenerate.

    In this PR, the meaning of ``threshold`` is that for all values of tau of G(tau), the value of a matrix element has to be smaller that ``threshold`` in order to set it to zero. So, the meaning of threshold has not really changed, just before only G(tau) at tau=beta was considered, now all taus are considered.

**Comment by gkraberger** [comment]
In this commit, I added the possibility to treat GfReFreq and GfReTime. Furthermore, I got rid of the conjugate_in_tau function, because it can be shown that to achive that it suffices to transpose the Green's function.

**Comment by mzingl** [comment]
Hi Gernot,
I have just one last question:
The part from line 1045 to 1072 is a duplicate of line 897 to 924.
Would it make sense to put this in a separate function?
Best,
Manuel

**Comment by dylex** [comment]
The analyze_block_structure_from_gf test is nondeterministically failing on linux (gcc and clang) with:
```
Traceback (most recent call last):
  File "/src/dft_tools/test/analyze_block_structure_from_gf.py", line 176, in <module>
    assert len(SK.deg_shells[0]) == 2, "wrong number of equivalent groups found"
AssertionError: wrong number of equivalent groups found
<end of output>
Test time =   8.71 sec
```
I just ran make test in a loop and it fails maybe 1 in 4 times.

**Comment by gkraberger** [comment]
Strange. The test features random numbers, so non-deterministic behavior is somehow expected. I did the same and ran it in a loop; in the 300 times I ran it, it failed just once. I will try to find a machine/setup where it fails more often so that I can investigate what goes wrong in the cases where it fails...

**Comment by gkraberger** [comment]
Ok, I found the reason. When a symmetry is found with and without conjugation, it is added twice. This is easy to fix, which I will push soon. Btw, a way to trigger the error is to put the line ``np.random.seed(1871466123)`` at the top of the ``analyze_block_structure_from_gf.py`` test.

However, after fixing the conjugation-bug, the test still fails which seems to be connected to a precision problem. I will have to think about that one...

**Comment by gkraberger** [comment]
The precision problem should be fixed now. The problem was that if the two blocks 1 and 2 are already symmetry-equivalent, i.e. there are unitary matrices v_1 and v_2 so that |v_1^dagger G_1 v_1 - v_2^dagger G_2 v_2| < threshold, and then 1 and 3 are checked and there is a matrix v_3 so that |v_1^dagger G_1 v_1 - v_3^dagger G_3 v_3| < threshold, we only know that |v_2^dagger G_2 v_2 - v_3^dagger G_3 v_3| < 2 x threshold.

Due to numerics (presumably), in practice, this does not even hold for 2 x threshold, but maybe only for 3   x threshold, (or even worse). This is why I used 10 x threshold for checking the equivalence of symmetries that were detected with threshold in the test now.

The doc of analyse_deg_shells now mentions that the symmetry might be broken by more than the threshold.

**Comment by mzingl** [comment]
I fixed the failing tests in commit d0ea51a1f532c040a0879cb9e59676fef582baa1

**Pull request merged**
