### PR TITLE
Add License and Authors file

### PR DESCRIPTION
**Pull request by Wentzell**
This commit adds a top-level LICENSE.txt, a copy of GPLv3 and a list of Authors in AUTHORS.txt

### CODE REVIEW

**Comment by Wentzell** [comment]
Should we remove the copyright information from the README in that case of should we synchronize it with the LICENSE.txt?

**Review by the-hampel — APPROVED** [review]

**Comment by mzingl** [comment]
Typo in authors: Aichhorn

**Comment by Wentzell** [comment]
@mzingl You should be able to correct any typos directly in the PR

Files Changed -> Edit File -> Commit

**Comment by mzingl** [comment]
Thanks, it was anyhow fixed by one of your commits.

**Review by mzingl — APPROVED** [review]

**Pull request merged**
