### PR TITLE
Elk Transport code and subsequent updates

### PR DESCRIPTION
**Pull request by AlynJ**
Hi @the-hampel, 

I've tagged @phibeck here too as I know she's working on updates to the transport code.

Here's my updates for transport calculations using Elk inputs. The following is a description of the updates I've made:

- I've updated the Elk interface routines to read in the required information for transport calculations. This includes python wrappers around a modified Fortran (Elk) code to read in the Elk momenta (velocities) in the PMAT.OUT binary file. Reading this file checks the k-points used to generate the file, so this will highlight any differences in k-meshes used. I've updated and added CMakeLists.txt files which handle the wrappers in the compilation.
- Minor updates in the transport code in sumk_dft_tools.py. This includes determining which DFT interface inputs to read in, fixing a MeshReFreq bug and making _cell_vol_ a global variable.
- I've updated the transport documentation which specifies how to get the transport inputs from either Wien2k and Elk. I've also included an example of DFT SrVO3. 
- I've introduced a new interface variable to be saved in dft_subgrp (for all DFT code interfaces) and read in by sumk_tools.py. I've called this _dft_code_ which specifies which DFT code the inputs came from. My reason for introducing this is to help the routines to automatically determine if they have been implemented for those DFT inputs which would help both development and user friendliness. For example, I've added an assertion for the partial_charges routine in sumk_dft_tools.py to only allow Wien2k inputs to be used, as I believe this routine has only been implement for Wien2k inputs. HDF5 files of calculations from previous versions of dft_tools would only need to have this variable added to them (via repacking from the respective interface or otherwise) in order to be compatible with this update. I think this variable should mainly be used to help handle reading in variables and prevent the user using certain routines with an assertion message if necessary. 
- Also, I've added a minor update which sets dm_type to _dft_code_ in the calc_density_correction routine within sumk_tools.py if the input of dm_type=None (which is now the default). Note that dm_type is still an input and can still be used as done previously.
- With the inclusion of _dft_code_, all reference HDF5 files used for testing the compilation have been updated to include this variable (set to the DFT code used for the test). The rest of the data within those files remain unchanged. I've also added a new test for the transport interface.  

Please let me know if you have any questions about any of this.

Kind regards,
Alyn

### CODE REVIEW

**Review by the-hampel — COMMENTED** [review]
Hi @AlynJ,
thank you for these updates! The changes look very good from my point of view. Special thanks for introducing the `dft_code` variable and storing it in the h5. This is something I mend to do a long time ago. I assume that you had to update all ref h5 archives because of this? Did you already check that besides the `dft_code` flag nothing else changed in the reference h5 archives? 

Besides this I think we can merge this in a few days, after others had the chance to look at it. I also have to check why the macos build fails. Somehow it seems that MacOS picks up a wrong gfortran compiler. But there is different fortran code in dft_tools that has to be compiled, which somehow works...

Best,
Alex

**Comment by phibeck** [comment]
Hi @AlynJ,
thanks for letting me know. As far as I can see this will be relatively straight-forward to merge with my changes. I agree that it's a good idea to set the `dft_code` and write it into the hdf5, too.
Best,
Sophie

**Comment by AlynJ** [comment]
Hi @the-hampel and @phibeck, 

I'm pleased to hear that you're happy with these updates! 

Regarding the updates to the ref h5 archives, I had a similar thought about keeping the rest of the data unchanged within them. Therefore, I used a python script which added the _dft_code_ variable into the .h5 files (if they contain the dft_subgrp) to ensure that I've not changed anything else. I've attached that python script (as a .txt file) here. I've also checked a reference .h5 file which remains unchanged except for the inclusion of _dft_code_.

Strange that the MacOS uses a different Fortran compiler. My guess is that these builds may have potentially failed because I've used Python wrappers to compile the Fortran code instead of directly compiling the code with the Fortran compiler. Hopefully that helps to figure out the cause of the failure!

Best,
Alyn
[add_dft_code_flag.txt](https://github.com/TRIQS/dft_tools/files/10006910/add_dft_code_flag.txt)

**Comment by the-hampel** [comment]
Ah very good. Then I am not concerned. I actually cross checked two h5 ref files and h5diff shows only exactly this change. Very good. I will coordinate on the MacOS problem, after this is solved we can merge.

**Comment by the-hampel** [comment]
Hi @AlynJ,
I think I forgot about the PR end of last year. I think everything is ready to be merged, correct? The Mac OS build crashes cannot be corrected right now. This is some incompatibility with the used macos version and libraries. Nothing to worry about. If you do not have anything to add I will merge everything today or tomorrow. 
Best,
Alex

**Comment by AlynJ** [comment]
Hi @the-hampel,

No problem! I have no further changes to add here, so I think this pull request is ready to be merged.

Best,
Alyn

**Pull request merged**
